### PR TITLE
Added a basic test for withdraw function

### PR DESCRIPTION
**Pull request by adityabhattad2021**

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Thanks! Just to keep the code the same as the video, I'm going to close this PR. Thank you though!

**Comment by adityabhattad2021** [comment]
No problem man, btw is there anything else I can help with?

**Comment by PatrickAlphaC** [comment]
Any help in the main repo answering questions would be appreciated!

https://github.com/smartcontractkit/full-blockchain-solidity-course-js

**Comment by adityabhattad2021** [comment]
Done 👍🏻

**Pull request closed without merging**
